### 1. 导入numpy库，并取别名为np

In [2]:
import numpy as np

### 2.创建一个长度为10，每个值都是0的numpy向量，并将第4个位置的值设置为1

In [4]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


### 3.  创建一个数值范围从10到50的numpy向量

In [5]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### 4.  将上题中的向量顺序翻转

In [6]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


### 5. 创建一个形状为3*3的随机numpy向量，每个数字范围0-1之间

In [7]:
Z = np.random.random((3,3))
print(Z)

[[0.747873   0.65094322 0.45261392]
 [0.84911356 0.08711393 0.09824855]
 [0.3929404  0.0071056  0.20710585]]


### 6.创建一个10x10 的numpy的随机向量，每个数字范围0-1之间，并找到其中的最大值和最小值

In [8]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.002642034838878926 0.9992818136282949


### 7.创建长度为30的随机numpy数组，并求其平均值

In [9]:
m= np.random.random(30)
m = Z.mean()
print(m)

0.4881934752980131


### 8.创建一个数字全是0的10*10的二维数组，并将其边界部分的数据全部设为1

In [10]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


### 9. 创建一个形状为8*8的二维numpy向量，并且这个向量不论每行还是每列看，都是0,1间隔的，如：
 [0 1 0 1 0 1 0 1]
 
 [1 0 1 0 1 0 1 0]
 
 [0 1 0 1 0 1 0 1]
 
 [1 0 1 0 1 0 1 0]
 
 [0 1 0 1 0 1 0 1]
 
 [1 0 1 0 1 0 1 0]
 
 [0 1 0 1 0 1 0 1]
 
 [1 0 1 0 1 0 1 0]
 

In [ ]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

### 10.创建一个长度为11的一维numpy数组，并且找到其中小于8且大于3的数

In [13]:
Z = np.arange(11)
Z=Z[(3 < Z) & (Z <= 8)] 
print(Z)

[4 5 6 7 8]
