### 1. 导入numpy库，并取别名为np

In [ ]:
import numpy as np

### 2.创建一个长度为10，每个值都是0的numpy向量，并将第4个位置的值设置为1

In [ ]:
z = np.zeros(10)
z[4] = 1
z

### 3.  创建一个数值范围从10到50的numpy向量

In [6]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

### 4.  将上题中的向量顺序翻转

In [15]:
z= np.arange(10,50)
z[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

### 5. 创建一个形状为3*3的随机numpy向量，每个数字范围0-1之间

In [16]:
np.random.random((3,3))

array([[0.69102563, 0.2741143 , 0.42656664],
       [0.03215125, 0.52275694, 0.16411816],
       [0.59295911, 0.12179378, 0.07316911]])

### 6.创建一个10x10 的numpy的随机向量，每个数字范围0-1之间，并找到其中的最大值和最小值

In [ ]:
z = np.random.random((10,10))
z,z.min(),z.max()

### 7.创建长度为30的随机numpy数组，并求其平均值

In [25]:
z = np.random.random(30)
z.mean()

0.5150704363528241

### 8.创建一个数字全是0的10*10的二维数组，并将其边界部分的数据全部设为1

In [29]:
z= np.ones((10,10))
z[1:-1,1:-1] = 0


array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [4]:
import numpy as np
z= np.ones((10,10))
z[1:-1 ,1:-1 ] = 0
z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

### 9. 创建一个形状为8*8的二维numpy向量，并且这个向量不论每行还是每列看，都是0,1间隔的，如：
 [0 1 0 1 0 1 0 1]
 
 [1 0 1 0 1 0 1 0]
 
 [0 1 0 1 0 1 0 1]
 
 [1 0 1 0 1 0 1 0]
 
 [0 1 0 1 0 1 0 1]
 
 [1 0 1 0 1 0 1 0]
 
 [0 1 0 1 0 1 0 1]
 
 [1 0 1 0 1 0 1 0]
 

In [7]:
z = np.zeros((8,8))
z[::2,1::2] = 1
z[1::2,0::2] = 1
z

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [33]:
z = np.zeros((8,8))
z[::2,1::2] =1
z[1::2,::2] =1 
z

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

### 10.创建一个长度为11的一维numpy数组，并且找到其中小于8且大于3的数

In [34]:
z= np.arange(11)
ppp = (3<z) &(z<8)
z[ppp]

array([4, 5, 6, 7])